//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPFriend.JenkinsOnDesktop.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XPFriend.JenkinsOnDesktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {Title} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BalloonTip_Title {
            get {
                return ResourceManager.GetString("BalloonTip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] CalmJ_feel {
            get {
                object obj = ResourceManager.GetObject("CalmJ_feel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] CJS_main {
            get {
                object obj = ResourceManager.GetObject("CJS_main", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] CJS_main_ja_JP {
            get {
                object obj = ResourceManager.GetObject("CJS_main_ja_JP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Configuration_ApplyButton {
            get {
                return ResourceManager.GetString("Configuration_ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Business に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Configuration_Business {
            get {
                return ResourceManager.GetString("Configuration_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Configuration_BusinessName {
            get {
                return ResourceManager.GetString("Configuration_BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Butler に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Configuration_Butler {
            get {
                return ResourceManager.GetString("Configuration_Butler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Configuration_ButlerName {
            get {
                return ResourceManager.GetString("Configuration_ButlerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Configuration_DiscardButton {
            get {
                return ResourceManager.GetString("Configuration_DiscardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Configuration Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Configuration_Open {
            get {
                return ResourceManager.GetString("Configuration_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Configuration_Parameter {
            get {
                return ResourceManager.GetString("Configuration_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Configuration_TimerInterval {
            get {
                return ResourceManager.GetString("Configuration_TimerInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jenkins に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName_CalmJenkins {
            get {
                return ResourceManager.GetString("DisplayName_CalmJenkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emotional Jenkins に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName_EmotionalJenkins {
            get {
                return ResourceManager.GetString("DisplayName_EmotionalJenkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] EmotionalJ_feel {
            get {
                object obj = ResourceManager.GetObject("EmotionalJ_feel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Invalid character : &apos;{0}&apos; ({1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_InvalidCharacter {
            get {
                return ResourceManager.GetString("Error_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   the script must return a instance of {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_TheScriptMustReturnObject {
            get {
                return ResourceManager.GetString("Error_TheScriptMustReturnObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap jenkins {
            get {
                object obj = ResourceManager.GetObject("jenkins", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon jenkins_icon {
            get {
                object obj = ResourceManager.GetObject("jenkins_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   jenkins.png and jenkins_icon.ico by the Jenkins project (http://jenkins-ci.org/) / CC BY-SA 3.0.
        ///
        ///Butler.xml and feel.ps1 by XPFriend Community (http://xpfriend.com/) / the MIT License. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License_CalmJenkins {
            get {
                return ResourceManager.GetString("License_CalmJenkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   jenkins.png and jenkins_icon.ico by the Jenkins project (http://jenkins-ci.org/) / CC BY-SA 3.0.
        ///
        ///sad.png, oni.png, onibi.png and ninja.png by Masanobu Imai (http://d.hatena.ne.jp/masanobuimai/) / CC BY-SA 3.0.
        ///
        ///Butler.xml and feel.ps1 by XPFriend Community (http://xpfriend.com/) / the MIT License. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License_EmotionalJenkins {
            get {
                return ResourceManager.GetString("License_EmotionalJenkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {Subject} {CurrentStatus} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_Report {
            get {
                return ResourceManager.GetString("Message_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jenkins に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Nickname_CalmJenkins {
            get {
                return ResourceManager.GetString("Nickname_CalmJenkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jenkins に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Nickname_EmotionalJenkins {
            get {
                return ResourceManager.GetString("Nickname_EmotionalJenkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ninja {
            get {
                object obj = ResourceManager.GetObject("ninja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Call {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyIcon_CallTheButler {
            get {
                return ResourceManager.GetString("NotifyIcon_CallTheButler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotifyIcon_Quit {
            get {
                return ResourceManager.GetString("NotifyIcon_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap oni {
            get {
                object obj = ResourceManager.GetObject("oni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap onibi {
            get {
                object obj = ResourceManager.GetObject("onibi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap sad {
            get {
                object obj = ResourceManager.GetObject("sad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] TK_main {
            get {
                object obj = ResourceManager.GetObject("TK_main", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] TK_main_ja_JP {
            get {
                object obj = ResourceManager.GetObject("TK_main_ja_JP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Window_Exit {
            get {
                return ResourceManager.GetString("Window_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Configuration... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Window_Show_Configuration {
            get {
                return ResourceManager.GetString("Window_Show_Configuration", resourceCulture);
            }
        }
    }
}
